config/routes.rb
Rails.application.routes.draw do
  resources :registered_applications, except: [:edit, :update]

  devise_for :users

  namespace :api, defaults: {format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end
  
  root 'welcome#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :registered_applications, dependent: :destroy
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController

  skip_before_action :verify_authenticity_token
  before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
    
    if registered_application == nil
      render json: "Unregistered application", status: :unprocessable_entity
    end
    
    @event = registered_application.events.new(event_params)

    if registered_application.save
      render json: @event, status: :created
    else
      render json: {errors: @event.errors}, status: :unprocessable_entity
    end
  end

  def preflight
    head 200
  end

  private
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :authenticate_user!

  def new
    @registered_application = RegisteredApplication.new
  end

  def create
    @registered_application = RegisteredApplication.new(registered_application_params)
    @registered_application.user = current_user
    if @registered_application.save
      flash[:notice] = "Application was saved."
      redirect_to @registered_application
    else
      flash.now[:alert] = "There was an error saving the application."
      render :new
    end
  end

  def destroy
    @registered_application = RegisteredApplication.find(params[:id])
    if @registered_application.destroy
      flash[:notice] = "\"#{@registered_application.name}\" has been deleted."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the topic."
      render :show
    end
  end
  
  def index
    @registered_applications = RegisteredApplication.all.where(user_id: current_user.id)
  end

  def show
    @registered_application = RegisteredApplication.find(params[:id])
    @events_group = @registered_application.events.group_by(&:name)
    @events = @registered_application.events.group_by(&:name)
  end

  private
    def registered_application_params
      params.require(:registered_application).permit(:name, :url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash_messages.html.erb
<div class="flash">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
    </div>
  <% elsif flash.now[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash.now[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<ul class="nav nav-tabs">
  <li><%= link_to "Blocmetrics", root_path %></li>
  <% if current_user %>
    <li><%= link_to "My Apps", registered_applications_path %></li>
    <li><%= link_to "New App", new_registered_application_path %></li>
  <% end %>
     
  <div class="pull-right user-info">
    <% if current_user %>
      Hello <%= current_user.email %> | <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %> or
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
  </div>
</ul>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmetrics</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container">
      
      <%= render 'layouts/header' %>
    
      <%= render 'layouts/flash_messages' %>
    
  <%= yield %>

  </div>
  </body>
</html>

app/views/registered_applications/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><h4>Registered Applications</h4></div>
  <table class = "table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>URL</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
     
    <tbody>
      <% @registered_applications.each do |registered_application| %>
        <tr>
          <td><%= link_to registered_application.name, registered_application %></td>
          <td><%= registered_application.url %></td>
          <td>
            <%= link_to registered_application_path(registered_application), method: :delete do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </td>
        </tr>    
      <% end %>  
    </tbody>  
  </table>
</div>

<br>

<p><%= link_to "Add Application", new_registered_application_path, class: "btn btn-sm btn-success" %></p>

app/views/registered_applications/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><h2>New Application Form</h2></div>
  <div class="panel-body">
    <br>
    <%= form_for @registered_application do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Enter name of application" %>
      </div>
      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: "form-control", placeholder: "Enter URL of application" %>
      </div>
      <%= f.submit "Submit" %>
    <% end %>
  </div>
</div>

app/views/registered_applications/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><h4>Registered Application</h4></div>
  <table class="table  table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>URL</th>
        <th>Events</th>
        <th></th>
      </tr>
     </thead>
    <tbody>
      <tr>
        <td><%= @registered_application.name %></td>
        <td><%= @registered_application.url %></td>
        <td><%= @events.count %></td>
        <td><%= link_to "Delete", registered_application_path, class: 'btn btn-sm btn-danger', method: :delete %></td>
      </tr>    
    </tbody>  
  </table>
</div>

<p><%= link_to "Add Application", new_registered_application_path, class: "btn btn-sm btn-success" %></p>

<br>
<br>

<div class="panel panel-primary">
  <div class="panel-heading"><h4>Events</h4></div>
  <table class="table table-striped table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Count</th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
      <tr>
        <td><%= event.first %></td>
        <td><%= event[1].length %></td>
        <% end %>
      </tr>
    </tbody>
  </table>
  <div class="panel panel-default">
    <div class="panel-body"><%= pie_chart @registered_application.events.group(:name).count %></div>
    <div class="panel-footer panel-info"><h3 class="text-center">Pie Chart</h3></div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <h1>Blocmetrics</h1>
  <h2><small >An analytics service and reporting tool that you can use with web apps to track user activity.</small></h2>
  
  <br>
  
  <div class="row">
    <% if user_signed_in? %>
      <div class="col-md-6"><p><%= link_to "My Registered Applications", registered_applications_path, class: "btn btn-primary" %></p></div>
      <div class="col-md-6"><p><%= link_to "New Web Application", new_registered_application_path, class: "btn btn-primary" %></p></div>
    <% else %>
      <div class="col-md-12">
        <p>
          <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
        </p>
      </div>
      <div class="row">
        <div class="col-sm-12 text-danger text-center">To test app with seeded data sign in with email: example3@yahoo.com | password: helloworld</div>
      </div>
    <% end %>   
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-info">
      <div class="panel-heading"><h3 class="text-center">Tracks User Activities</h3></div>
      <div class="panel-body"><%= image_tag("graph1.png", width: '433', height: '433', alt: "Bar chart", class: "center-block img-responsive") %></div>
    </div>  
  </div>

  <div class="col-md-6">
    <div class="panel panel-info">
      <div class="panel-heading"><h3 class="text-center">Easily Readable Chart</h3></div>
      <div class="panel-body"><%= image_tag("graph2.png", alt: "Pie chart", class: "center-block img-responsive") %></div>
    </div>  
  </div>
</div>

    